### ISSUE TITLE
Repeated IDs and multiple instance use case

### ISSUE THREAD

**Issue by ikenne** [osamingo/indigo#40]
I  am hoping to use this in some code for generating unique max 11 character IDs.

A couple of questions:

i) Can the library be used where different instances of a code, say in a Lambda Functions, need to get a unique ID, or there needs to be a running server, coordinating the IDs?
ii) I tried a small unit test:
```
g := indigo.New(nil, indigo.StartTime(time.Now()))

id1, err := g.NextID()
if err != nil {
	t.Error("should be nil")
}

fmt.Println(id1)

id2, err := g.NextID()
if err != nil {
	t.Error("should be nil")
}

fmt.Println(id2)
```
 
I was getting same values for different executions of the test:
>=== RUN   TestIndigoID
>nvReu8adFt
>nvReu8axjp
>
>=== RUN   TestIndigoID
>nvReu8adFt
>nvReu8axjp

Another set of consecutive runs:
>=== RUN   TestIndigoID
>2Uzir
>2VLCn
>
>=== RUN   TestIndigoID
>2Uzir
>2VLCn
Does this mean it starts from an initial value whenever there is a call to `indigo.New`?

Thanks

**Comment by lengthmin** [comment]
maybe related to rand seed

> Random numbers are generated by a Source. Top-level functions, such as Float64 and Int, use a default shared Source that produces a deterministic sequence of values each time a program is run

see <https://golang.org/pkg/math/rand/>

**Comment by osamingo** [comment]
@ikenne Hi, sorry for the late reply.

The result is correct, because the StartTime is using Now, and the result changes because of the fluctuation in elapsed time from that time, which is the correct behavior.

When you actually use it in your Application, you should use it with a fixed StartTime.
If you want to know more, read the README at https://github.com/sony/sonyflake.

Best regards,
